import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'TheResumeCompany terms of service — rules and guidelines for using our platform.',
}

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:py-24">
      <h1 className="text-4xl font-bold tracking-tight">Terms of Service</h1>
      <p className="mt-2 text-sm text-muted-foreground">Last updated: March 15, 2026</p>

      <div className="prose prose-sm mt-10 max-w-none text-muted-foreground [&_h2]:mt-10 [&_h2]:text-lg [&_h2]:font-semibold [&_h2]:text-foreground [&_p]:mt-3 [&_ul]:mt-3 [&_ul]:list-disc [&_ul]:pl-6">
        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using TheResumeCompany (&ldquo;Service&rdquo;), you agree to be bound by these
          Terms of Service. If you do not agree, please do not use the Service.
        </p>

        <h2>2. Account Registration</h2>
        <p>
          You must provide accurate information when creating an account. You are responsible for
          maintaining the security of your account credentials. You must be at least 16 years old
          to use the Service.
        </p>

        <h2>3. Credits and Payments</h2>
        <ul>
          <li>New accounts receive 100 free credits</li>
          <li>Credits are consumed when using AI features and PDF exports</li>
          <li>Credit packs are non-refundable one-time purchases</li>
          <li>Pro subscriptions can be canceled anytime — you retain access until the billing period ends</li>
          <li>We reserve the right to modify pricing with 30 days notice</li>
        </ul>

        <h2>4. AI-Generated Content</h2>
        <p>
          Content generated by our AI features is provided as suggestions. You are responsible for
          reviewing, editing, and ensuring the accuracy of all content in your resume. We do not
          guarantee that AI-generated content is factually accurate or free of errors.
        </p>
        <p>
          You retain full ownership of all resume content you create, including AI-assisted content.
          We do not claim any intellectual property rights over your resumes.
        </p>

        <h2>5. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service to create fraudulent or misleading resumes</li>
          <li>Attempt to manipulate or abuse the credit system</li>
          <li>Use automated tools to access the Service beyond normal usage</li>
          <li>Interfere with or disrupt the Service or its infrastructure</li>
          <li>Share your account credentials with others</li>
        </ul>

        <h2>6. Intellectual Property</h2>
        <p>
          The Service, including its design, templates, and AI technology, is owned by
          TheResumeCompany. Our templates are provided for personal use in creating resumes and
          may not be redistributed, resold, or used for commercial template distribution.
        </p>

        <h2>7. Limitation of Liability</h2>
        <p>
          The Service is provided &ldquo;as is&rdquo; without warranties of any kind. We are not liable for any
          indirect, incidental, or consequential damages arising from your use of the Service,
          including but not limited to job application outcomes.
        </p>

        <h2>8. Account Termination</h2>
        <p>
          We reserve the right to suspend or terminate accounts that violate these terms. You may
          delete your account at any time from the Settings page. Upon termination, your data
          will be deleted in accordance with our Privacy Policy.
        </p>

        <h2>9. Changes to Terms</h2>
        <p>
          We may modify these terms at any time. Continued use of the Service after changes
          constitutes acceptance. We will notify you of material changes via email.
        </p>

        <h2>10. Governing Law</h2>
        <p>
          These terms are governed by and construed in accordance with applicable law. Any
          disputes will be resolved through binding arbitration.
        </p>

        <h2>11. Contact</h2>
        <p>
          For questions about these terms, contact us at legal@theresumecompany.com.
        </p>
      </div>
    </div>
  )
}
