export const TEMPLATE_NAMES: Record<string, string> = {
  // Professional (9)
  'classic-professional': 'Classic Professional',
  executive: 'Executive',
  corporate: 'Corporate',
  'elegant-serif': 'Elegant Serif',
  oxford: 'Oxford',
  blueprint: 'Blueprint',
  consulting: 'Consulting',
  diplomat: 'Diplomat',
  'refined-gold': 'Refined Gold',
  // Modern (8)
  'modern-minimal': 'Modern Minimal',
  metro: 'Metro',
  sleek: 'Sleek',
  'noir-edge': 'Noir Edge',
  'vibrant-pop': 'Vibrant Pop',
  'fresh-start': 'Fresh Start',
  'impact-one': 'Impact One',
  'bright-spark': 'Bright Spark',
  // Creative (7)
  'creative-bold': 'Creative Bold',
  designer: 'Designer',
  starter: 'Starter',
  mosaic: 'Mosaic',
  'pixel-art': 'Pixel Art',
  origami: 'Origami',
  timeline: 'Timeline',
  // Tech (8)
  developer: 'Developer',
  data: 'Data',
  'devops-pipeline': 'DevOps Pipeline',
  'cloud-architect': 'Cloud Architect',
  'cyber-matrix': 'Cyber Matrix',
  'quantum-bits': 'Quantum Bits',
  fintech: 'Fintech',
  ledger: 'Ledger',
  // ATS-Optimized (6)
  'ats-simple': 'ATS Simple',
  'ats-professional': 'ATS Professional',
  'healthcare-vitals': 'Healthcare Vitals',
  'legal-brief': 'Legal Brief',
  'government-service': 'Government Service',
  'nonprofit-mission': 'Nonprofit Mission',
  // Academic (4)
  'academic-cv': 'Academic CV',
  'educator-classic': 'Educator Classic',
  'research-lab': 'Research Lab',
  'ivy-league': 'Ivy League',
  // Minimal (12)
  'clean-slate': 'Clean Slate',
  'heritage-serif': 'Heritage Serif',
  'premium-edge': 'Premium Edge',
  catalyst: 'Catalyst',
  'zen-master': 'Zen Master',
  'whisper-light': 'Whisper Light',
  'paper-cut': 'Paper Cut',
  'airy-space': 'Airy Space',
  'nordic-frost': 'Nordic Frost',
  'clean-line': 'Clean Line',
  'zen-garden': 'Zen Garden',
  'bare-minimum': 'Bare Minimum',
}
